make:
	curl --insecure -F "bmd_file=@bmd.xml" https://localhost:8888/bmd 
	curl --insecure -F "bmd_file=@bmd1.xml" https://localhost:8888/bmd 
	curl --insecure -F "bmd_file=@bmd2.xml" https://localhost:8888/bmd 
	curl --insecure -F "bmd_file=@bmd3.xml" https://localhost:8888/bmd 
	curl --insecure -F "bmd_file=@bmd4.xml" https://localhost:8888/bmd 
	curl --insecure -F "bmd_file=@bmd5.xml" https://localhost:8888/bmd	


